repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.3.2
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: ['dbt-postgres', 'sqlfluff-templater-dbt']
        args: [--dialect=postgres]
        files: \.(sql|SQL)$
      - id: sqlfluff-fix
        additional_dependencies: ['dbt-postgres', 'sqlfluff-templater-dbt']
        args: [--dialect=postgres]
        files: \.(sql|SQL)$
        stages: [manual]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files