name: shittheyleaveonourstreets
description: Shit they leave on our streets
publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/image1.jpeg
    - assets/image2.jpeg
    - assets/image3.jpeg
    - assets/image4.jpeg
    - assets/image5.jpeg
    - assets/image6.jpeg
    - assets/image7.jpeg
    - assets/image8.jpeg
    - assets/image9.jpeg
    - assets/image10.jpeg
    - assets/image11.jpeg
    - assets/image12.jpeg
    - .env.local
    - .env.production
