name: shittheyleaveonourstreets
description: Shit they leave on our streets
publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image1.jpeg
    - assets/image2.jpeg
    - assets/image3.jpeg
