name: Deploy Database

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      args:
        description: "Any args to supabase db as single string"
        required: true
        type: string
  push:
    branches: [main]
    paths:
      - "supabase/**"

jobs:
  deploy_db:
    name: Deploy DB
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          clean: false

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

      - run: supabase db push
        if: ${{ github.event_name == 'push' }}
        env:
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

      - run: bash -c "echo 'y' | supabase db ${ARGS:-}"
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          ARGS: ${{ inputs.args }}
